# Snowflake Connection Secrets
[snowflake]
account = "xy12345.us-east-1"
user = "STREAMLIT_USER"
password = "YourSecurePassword123!"
warehouse = "COMPUTE_WH"
database = "CROP_RECOMMENDATION"
schema = "ML_MODELS"
role = "ACCOUNTADMIN"
